sequenceDiagram
    actor User
    User ->> Menu : run
    activate Menu
    Menu ->> BeatmapTUI : startMenu
    activate BeatmapTUI
    BeatmapTUI ->> InputService : getString
    activate InputService
    InputService -->> BeatmapTUI : #32; 
    deactivate InputService
    BeatmapTUI ->> BeatmapService : saveBeatmapFromJsonString
    activate BeatmapService
    BeatmapService ->> BeatmapService : beatmapFromJsonString
    BeatmapService ->> BeatmapService : save
    BeatmapService -->> BeatmapTUI : #32;
    deactivate BeatmapService
    BeatmapTUI ->> OsuLog : info
    activate OsuLog
    OsuLog -->> BeatmapTUI : #32; 
    deactivate OsuLog
    BeatmapTUI -->> Menu : #32; 
    deactivate BeatmapTUI
    deactivate Menu
